### ISSUE TITLE
Render inter-compatible type-definition files

### ISSUE THREAD

**Issue by candrews** [CycloneDX/cyclonedx-javascript-library#291]
If this library published inter-compatible type-definitions, it would facilitate the use of the library by projects that use other versions of typescript.

For example, see https://github.com/snyk/cli/pull/3983#issuecomment-1288117901

Thank you!

**Comment by jkowalleck** [comment]
damned, i got away with my crappy abuse of the source-files for too long ;-) 

will see what i can do.

**Comment by jkowalleck** [comment]
to give some context: there is nothing wrong  with the current method of announcing the type declarations based on the actual source code.
the actual source code targets TypeScript v4.8

if downstream users of the library compile with a typescript version that does not fully understand all features that are used, or has a different config regarding the compatibility-settings, then that downstream compiler crashes.

to mitigate these crashes, it is desired to render and announce type declarations that are not inter-compatible to most popular versions of typescript (v3.X, v4.X)
so that the user base is not restricted in their usage of typescript.

**Comment by jkowalleck** [comment]
@candrews could you bump your dependency to this lib to `^1.7.0` and see if yoi can digest the new type declarations that are now shipped?

**Comment by candrews** [comment]
> could you bump your dependency to this lib to `^1.7.0` and see if yoi can digest the new type declarations that are now shipped?

Done! That was easy. The diff for the PR at https://github.com/snyk/cli/pull/3983 is now much smaller. Thank you!

**Comment by jkowalleck** [comment]
no worries. thanks for pushing this feature forward. 
i just needed a good reason to generate these declaration files.
